### PR TITLE
Create Infinite Tower Level

### PR DESCRIPTION
**Pull request by RoundEggy**
## Description
<!--Prodigy is hacked haha--!>
Prodigy is hacked haha

### CODE REVIEW

**Comment by ArcerionDev** [comment]
duplicate

**Comment by SwxtchCode** [comment]
assume good faith

**Comment by RoundEggy** [comment]
> duplicate

Duplicate of what? it was my own idea

**Comment by PatheticMustan** [comment]
It doesn't even work, `getTowerprogress` should be `getTowerProgress`

**Comment by RoundEggy** [comment]
> It doesn't even work, `getTowerprogress` should be `getTowerProgress`

are you sure it worked for me

**Comment by RoundEggy** [comment]
> > It doesn't even work, `getTowerprogress` should be `getTowerProgress`
> 
> are you sure it worked for me

as long as the spelling is good, it works

**Comment by PatheticMustan** [comment]
javascript is case sensitive, so this wouldn't have worked.

**Comment by RoundEggy** [comment]
> javascript is case sensitive, so this wouldn't have worked.

i got the x-frame extention and went to the console in prodigy and it worked sooo....

**Pull request closed without merging**
