### PR TITLE
Hack Request

### PR DESCRIPTION
**Pull request by FelixN0324**
Allows you go past monsters!

### CODE REVIEW

**Comment by Jedimaster05** [comment]
2 things if I could I would like to a collerbrator just need to know what to do 2 could you hack my prodigy account I would but I using a school computer so redirector and console wont work.

**Comment by Jedimaster05** [comment]
I,ll help others everyday If I can Im a very active person a friendly face in here if needed.Can remind others of the rules to and whats required of me

**Comment by Jedimaster05** [comment]
If you can hack my account I,ll tell it to you thank you have a good day

**Comment by Avn1114** [comment]
Huh @FelixN0324 Looks gud, I was wondering where this was, thanks :)

**Comment by SportsandGameaddict** [comment]
what?

**Comment by SportsandGameaddict** [comment]
can you hack my account please noone will help me
User Codyb6308
password 1234
Thank you sorry for bugging you and taking your time have a good day

**Comment by PatheticMustan** [comment]
@SportsandGameaddict invalid creds, can't log in :P

**Pull request merged**
