### PR TITLE
Weekly Gramdar™

### PR DESCRIPTION
**Pull request by ChickenOnYT**
## Description
once a week passes i rebase all the commits in my fork into one and push my Weekly Gramdar™ fixes

## Screenshots
no

### CODE REVIEW

**Comment by PatheticMustan** [comment]
Bruh ok

**Comment by ArcerionDev** [comment]
fair enough

**Comment by ChickenOnYT** [comment]
a week hadnt passed yet i was gonna merge this on sat lmao

**Comment by ChickenOnYT** [comment]
incase i find more grammar changes

**Pull request merged**
