### PR TITLE
Hacks don't work

### PR DESCRIPTION
**Pull request by jhatton2027**
pordigy i think it work

### CODE REVIEW

**Comment by jhatton2027** [comment]
why i t not working

**Comment by BoredFishRE** [comment]
bruh wat

**Comment by ChickenOnYT** [comment]
> why i t not working

Please provide more information.

**Comment by NX721** [comment]
The file you changed, it can't do anything.

**Comment by BoredFishRE** [comment]
Bro it's a pull request. If they want help, they need to make an issue

**Comment by ChickenOnYT** [comment]
Oh, I thought it was an issue. My bad.

**Pull request closed without merging**
