### PR TITLE
Pause Game hack

### PR DESCRIPTION
**Pull request by donaldli2020**
## Description

Add Pause Game from ```_.network```

### CODE REVIEW

**Comment by hostedposted** [comment]
please fix the issue

**Comment by hostedposted** [comment]
also please remove the
``// I sort of copied this code because I don't get it.`` and ``// Make corrections please.`` comment.

**Comment by donaldli2020** [comment]
Oops, I left out the quotation mark.

**Comment by donaldli2020** [comment]
Oops, I left out the comma.

**Comment by donaldli2020** [comment]
Hello, @hostedposted. Can you merge?

**Review by PatheticMustan — APPROVED** [review]

**Pull request merged**
