### PR TITLE
add extension

### PR DESCRIPTION
**Pull request by NameIsA**
it will be transferred to pmgh later anyway (waiting on google support), it's unlikely that i would screw something up in like 2 days. the extension is simpler to install from the web store.

### CODE REVIEW

**Comment by BoredFishRE** [comment]
bruh no that's the link to how to install. If anything, change the link in how to install. But like let's wait until it transfers to us so your email won't commit die with all the skids emailing it.

**Comment by NameIsA** [comment]
> bruh no that's the link to how to install. If anything, change the link in how to install. But like let's wait until it transfers to us so your email won't commit die with all the skids emailing it.

why would my email die because of skids emailing it

i get emailed and messaged by skids a lot idrc about it

**Comment by NameIsA** [comment]
but i do need to build it lemme do that

**Comment by BoredFishRE** [comment]
i've already built

**Comment by NameIsA** [comment]
> i've already built

ok

i just dont know how long it will take for it to be transferred to you and i have ownership of it right now so once google approves the description update i can fix the extension and i'll have to fix it if you dont have ownership at the time

**Pull request closed without merging**
