### PR TITLE
fix walk speed

### PR DESCRIPTION
**Pull request by donaldli2020**
## Description

fix walkspeed

### CODE REVIEW

**Comment by hostedposted** [comment]
NumberInput only allows integers. So that's why we were using Input.

**Comment by donaldli2020** [comment]
Input is not defined, so I used numberinput.

**Comment by hostedposted** [comment]
yes it is

**Comment by hostedposted** [comment]
well it should be

**Comment by donaldli2020** [comment]
I got it in the console.

**Comment by hostedposted** [comment]
Well Arc forgot to add Input when making the section

**Comment by ArcerionDev** [comment]
asdfghjkl this is what happens when you're trying to hurry with something

**Pull request closed without merging**
