### PR TITLE
removing buddies that trigger 418

### PR DESCRIPTION
**Pull request by ArcerionDev**
making this a pr in case the 418 anticheat was removed as was speculated the other day (@32n ? )

### CODE REVIEW

**Comment by ArcerionDev** [comment]
also if my code can be golfed let me know, there's probably an easier way to do this

**Comment by Erisfiregamer1** [comment]
It was not. It is still VERY active, sadge

**Review by donaldli2020 — APPROVED** [review]
Awesome!

**Comment by afkvido** [comment]
ya

**Comment by donaldli2020** [comment]
woohoo

**Pull request merged**
