### PR TITLE
get rid of hacks folder

### PR DESCRIPTION
**Pull request by ConnorAhern**
#1167 

Somebody once told me the world is gonna roll me
I ain't the sharpest tool in the shed
She was looking kind of dumb with her finger and her
Thumb in the shape of an "L" on her forehead

Well the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb
So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow

Hey now you're an All Star get your game on, go play
Hey now you're a Rock Star get the show on get paid
(And all that glitters is gold)
Only shooting stars break the mold

It's a cool place and they say it gets colder
You're bundled up now but wait 'till you get older
But the meteor men beg to differ
Judging by the hole in the satellite picture

The ice we skate is getting pretty thin
The waters getting warm so you might as well swim
My world's on fire how about yours
That's the way I like it and I never get bored

Hey now you're an All Star get your game on, go play
Hey now you're a Rock Star get the show on get paid
(And all that glitters is gold)
Only shooting stars break the mold

Hey now you're an All Star get your game on, go play
Hey now you're a Rock Star get the show on get paid
(And all that glitters is gold)
Only shooting stars

Somebody once asked, "could I spare some change for gas
I need to get myself away from this place"
I said yep what a concept
I could use a little fuel myself
And we could all use a little change.

Well the years start coming and they don't stop coming
Fed to the rules and I hit the ground running
Didn't make sense not to live for fun
Your brain gets smart but your head gets dumb
So much to do so much to see
So what's wrong with taking the back streets
You'll never know if you don't go
You'll never shine if you don't glow

Hey now you're an All Star get your game on, go play
Hey now you're a Rock Star get the show on get paid
(And all that glitters is gold)
Only shooting stars break the mold

(And all that glitters is gold)
Only shooting stars break the mold

### CODE REVIEW

**Review by ConnorAhern — COMMENTED** [review]
my changes are good, go approve 'em

**Review by PatheticMustan — APPROVED** [review]
LGTM

**Comment by 32n** [comment]
YESSS thank you @PatheticMustan @ConnorAhern

This is a necessary first step to restructuring the repo/making it neater.

**Comment by ConnorAhern** [comment]
you're welcome messier arc

**Comment by 32n** [comment]
I prefer to think of myself as artistic arc

**Comment by ConnorAhern** [comment]
ok

**Comment by ArcerionDev** [comment]
arctistic

**Comment by ConnorAhern** [comment]
> arctistic

that sounds like something AGR would say as like "arc is autistic" because AGR's catchphrase is calling people autistic

**Comment by AgrTheDev** [comment]
> > arctistic
> 
> that sounds like something AGR would say as like "arc is autistic" because AGR's catchphrase is calling people autistic

Buddy I literally called you autistic because it’s the only word in the world to ever describe you. You own a prodigy fan server and cry about people hacking and here you are posting literally every day on here. You were malding about the gc agreeing to not support raging gay people and then come back and spam racial slurs and death threats. You tried to profit off of making hacked accounts and using ads and miss advertising them as “mobile hacks”. So yes, if you don’t think the word autistic describes you then I have no idea what you’re thinking.

**Comment by ConnorAhern** [comment]
> > > arctistic
> > 
> > 
> > that sounds like something AGR would say as like "arc is autistic" because AGR's catchphrase is calling people autistic
> 
> Buddy I literally called you autistic because it’s the only word in the world to ever describe you. You own a prodigy fan server and cry about people hacking and here you are posting literally every day on here. You were malding about the gc agreeing to not support raging gay people and then come back and spam racial slurs and death threats. You tried to profit off of making hacked accounts and using ads and miss advertising them as “mobile hacks”. So yes, if you don’t think the word autistic describes you then I have no idea what you’re thinking.

i own a prodigy fan server, whats the problem with that?

i didnt "cry about people hacking"

i didnt spam death threats/racial slurs wtf lmao

what are you even going on about

**Comment by AgrTheDev** [comment]
image

**Comment by ConnorAhern** [comment]
oh yeah

**Comment by ConnorAhern** [comment]
idk why i said that

**Comment by 32n** [comment]
Guys, this isn't a thing you should be talking about on the repo.

**Comment by ConnorAhern** [comment]
> Guys, this isn't a thing you should be talking about on the repo.

aw man i wanted to have a petty argument with a random dude i hardly know :((

**Comment by 32n** [comment]
A little funny stuff is fine on Github, but you are like... spamming song lyrics on PRs and having public arguments. Could you please not. I don't own the repo, but it's a little annoying to see.

**Comment by AgrTheDev** [comment]
You hardly know me yet you have the reasoning to call me a "mega gay nigga fag", reasonable.

**Comment by ConnorAhern** [comment]
> You hardly know me yet you have the reasoning to call me a "mega gay nigga fag", reasonable.

AS I SAID IT WAS A QUOTE BUT I WAS CALLING YOU IT

**Comment by ConnorAhern** [comment]
> A little funny stuff is fine on Github, but you are like... spamming song lyrics on PRs and having public arguments. Could you please not. I don't own the repo, but it's a little annoying to see.

i put the song lyrics because there was no other info to add to the pr but i wanted to put some other stuff on it >:(

**Comment by PatheticMustan** [comment]
OI let's not talk about this in public. Please argue in DMs :((

**Pull request merged**
