### PR TITLE
Free Member Stars (Levels you up faster)

### PR DESCRIPTION
**Pull request by RoundEggy**
This hack makes you level up faster I tried it and it worked

### CODE REVIEW

**Review by RoundEggy — COMMENTED** [review]
#360

**Comment by PatheticMustan** [comment]
While we've already seen this, I see no reason why we can't add it to WCM

**Comment by RoundEggy** [comment]
> While we've already seen this, I see no reason why we can't add it to WCM. The only downside is the extremely long unskippable animation.

is this good or bad? what's a WCM? I'm new to github.

**Comment by BoredFishRE** [comment]
Will's cheat menu. It's the cheat menu

**Review by UntrustableRus — APPROVED** [review]
Made minor modifications, I think this commit is ready to merge.

**Comment by ArcerionDev** [comment]
This is not needed, level hack works the exact same way and takes less work.

**Review by IIDepressedII — COMMENTED** [review]
Why delete!!!

**Comment by PatheticMustan** [comment]
bookmarklets are legacy, they don't work anymore unless you already have redirector, which kinda defeats the point of bookmarklets

**Comment by UntrustableRus** [comment]
ye bookmarklets aren´t really possible.

**Comment by RoundEggy** [comment]
what happens if its ready to merge? sorry, I'm new to github and everythings kinda confusing i just did some random stuff and I guess it kinds worked

**Review by williamf0140 — COMMENTED** [review]
how do you do it

**Comment by PatheticMustan** [comment]
@williamf0140 
[installation](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/wiki/How-to-install-hacks).

**Pull request merged**
