### PR TITLE
WASD movement

### PR DESCRIPTION
**Pull request by donaldli2020**
## Description

this is to see if webpack is working for me

### CODE REVIEW

**Review by afkvido — APPROVED** [review]
Actually, it looks good to me.

**Comment by donaldli2020** [comment]
It somehow made a folder called node_modules, whatever that is

**Comment by AgrTheDev** [comment]
> It somehow made a folder called node_modules, whatever that is
It's a folder where NPM modules are contained. I think you gotta put it in a .gitignore file but idk exactly

**Comment by afkvido** [comment]
@AgrTheDev 

node_modules is already in the gitignore

**Comment by afkvido** [comment]
> It somehow made a folder called node_modules, whatever that is

Those are required to do stuff like webpack bundle, build, etc

**Comment by donaldli2020** [comment]
theres like a million files inside

**Comment by donaldli2020** [comment]
and yes, it does ingore [node_modules/](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/.gitignore#L5)

**Comment by afkvido** [comment]
> theres like a million files inside

Mainly dependancies, and some other piss and shit

**Comment by 32n** [comment]
Don't make pull requests just to test things... they are for actual contributions, not messing around.

**Comment by afkvido** [comment]
> Don't make pull requests just to test things... they are for actual contributions, not messing around.

Wait, I've made one before and it got merged LMAO.

#1294: The PR itself was helpful, but it was sort of a test to see if i can use npm.

**Comment by 32n** [comment]
That's not a good thing to do. Pull requests aren't your personal testing grounds for code. The purpose of the PR did not appear to mainly be for testing, though.

**Comment by afkvido** [comment]
> That's not a good thing to do. Pull requests aren't your personal testing grounds for code. The purpose of the PR did not appear to mainly be for testing, though.

It wasn't **mainly** for testing. But it was one of the things I wanted to get out of the PR

**Pull request closed without merging**
