### PR TITLE
give 1e7 gold anyway

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by 32n** [comment]
This is a bad way to design things. The user didn't want 10,000,000 gold, don't set their gold to that amount. Also, prodigy's gold limit was addressed by #1184, please do not make further pull requests regarding it.

**Comment by PatheticMustan** [comment]
the user might not have wanted 10m gold, but they definitely wanted a lot of it. I think it was a reasonable change but unnecessary.

**Comment by 32n** [comment]
The issue is, the UI doesn't have gold count on display, and the user might not read the whole error. I know that I certainly don't carefully read every pop-up. Giving them 10,000,000 gold without them being fully aware could lead to them battling, getting the gold, and getting a 418.

**Comment by 32n** [comment]
I don't think we should set a hard limit like the one I set at 10mil, but it would probably be good to add a warning if users set their gold above 9mil.

**Pull request closed without merging**
