### PR TITLE
add other towers

### PR DESCRIPTION
**Pull request by donaldli2020**
## Description

tested

### CODE REVIEW

**Comment by TheFinality** [comment]
Please use webpack to compile it

**Comment by donaldli2020** [comment]
can you help with dist/bundle.ts

**Comment by donaldli2020** [comment]
it's laggy

**Comment by donaldli2020** [comment]
https://github.com/donaldli2020/ProdigyMathGameHacking/tree/patch-1

**Comment by Jes-debug** [comment]
how do i use ur fork @donaldli2020

**Comment by donaldli2020** [comment]
edit it

**Comment by Jes-debug** [comment]
? @donaldli2020

**Comment by ArcerionDev** [comment]
other towers either crash game or simply don't let you in

**Pull request closed without merging**
