### PR TITLE
Delete customCurrency.js

### PR DESCRIPTION
**Pull request by NX721**

### CODE REVIEW

**Comment by PatheticMustan** [comment]
for heck's sake, just make your changes on one branch, and make a PR when you'r edone

**Comment by NameIsA** [comment]
very nice job... an average dude using an underappreciated free service, then deciding to give back :'D

no need to know to code to help delete deprecated stuff

you're a nice guy :3

**Comment by NX721** [comment]
?

**Comment by BoredFishRE** [comment]
i'll just merge this.

**Pull request merged**
