### PR TITLE
adding a small detail

### PR DESCRIPTION
**Pull request by IhackProdigy**
## Description
adding a VERY small detail

## Screenshots
on a school computer so cant use dev mode to add the extension in

### CODE REVIEW

**Comment by IhackProdigy** [comment]
@TheFinality its blocked on my school computer :(
ill use my ipad :D

**Comment by TheFinality** [comment]
how is it blocked???? wtf

**Comment by ConnorAhern** [comment]
> how is it blocked???? wtf

well, these might have caused it:

> Easily hack your prodigy math game accounts online!
> Prodigy Account Hacker

@IhackProdigy could you screenshot the blocked message?

**Comment by IhackProdigy** [comment]
here is the screenshot (i drew out my email and ip)
Screenshot 2021-10-10 8 18 03 PM

**Pull request closed without merging**
