### PR TITLE
[WIP] Chrome & Firefox Extension Method

### PR DESCRIPTION
**Pull request by UntrustableRus**
This adds the chrome extension method to the documentation. This is unfinished, and I am awaiting for the extension to be accepted on the chrome web store, so do not accept/deny until the [WIP] tag is removed. The extension method will be the most easiest, you just download our extension and you are good to go.

**What is the extension hack?**
I made an official prodigy hacking extension, that does the exact same thing as redirector except you don't have to import any redirects or anything, you just download the extension from the chrome web store and you're good to go. This simplifies the method massively, and the extension has a smaller file size than the redirector extension.

**TODO**
- README.md [-] Change URL to go to extension instead of about:blank, do this once the extension gets approved on the CWS and then remove this PR as a draft and await approval.
- ~~Extension Itself (Extension code is not on this pull request) [-] Code Revisions~~
- ~~Extension Itself (Extension code is not on this pull request) [-] Remove X-Frame Headers~~

**Reasons the extension might be declined for CWS (Chrome Web Store)**
image

### CODE REVIEW

**Comment by ArcerionDev** [comment]
Maybe wait until it's public to announce it

**Comment by ArcerionDev** [comment]
Thanks :3

**Comment by UntrustableRus** [comment]
@ArcerionDev I didn't announce it? I'm just working on a PR to merge when it's finished.

**Comment by ArcerionDev** [comment]
Ah

**Review by PatheticMustan — CHANGES_REQUESTED** [review]
???? just write your name????

**Comment by UntrustableRus** [comment]
@PatheticMustan I did?

**Review by PatheticMustan — APPROVED** [review]

**Comment by PatheticMustan** [comment]
ok, so now just upload the plugin's source

**Comment by PatheticMustan** [comment]
@UntrustableRus, please upload the actual source to the plugin. Until then, we won't be able to merge this PR.

**Comment by ArcerionDev** [comment]
Just reopen this PR when you're ready to upload it @UntrustableRus :D

**Comment by UntrustableRus** [comment]
@ArcerionDev Ready for merge, this is only for the Firefox extension, the chrome extension will take a little longer than expected, and I'll make a separate PR for it, but for now, we can release the Firefox extension.

**Comment by PatheticMustan** [comment]
@UntrustableRus we ABSOLUTELY need the source code to be publicized before releasing it.

**Comment by LifeIsNull** [comment]
> Reasons the extension might be declined for CWS (Chrome Web Store)

It doesn't interfere with anything much, and it's not malware. I don't see the issue??

**Pull request closed without merging**
