### PR TITLE
Merge redirector

### PR DESCRIPTION
**Pull request by PatheticMustan**
DO NOT MERGE

### CODE REVIEW

**Comment by PatheticMustan** [comment]
GOD DAMNIT

**Comment by PatheticMustan** [comment]
YES, alright it worked

**Comment by PatheticMustan** [comment]
I may have force pushed an atrocity, but at least we get to keep commit history, huh

**Comment by PatheticMustan** [comment]
WAIT NEVERMIND GOD DAMNIT IT FAILED

**Comment by NameIsA** [comment]
very cool

**Pull request merged**
