### PR TITLE
Updated collaborators list in /docs

### PR DESCRIPTION
**Pull request by NameIsA**
## Description
I mean, nobody's even done anything about #298, so why not start?

## Screenshots
Now the collaborators list looks like this:

<a href="https://imgbb.com/">Screenshot-2</a>

### CODE REVIEW

**Comment by PatheticMustan** [comment]
tmw DCK is cut out

**Comment by NameIsA** [comment]
> tmw DCK is cut out

what does tmw stand for

**Comment by NameIsA** [comment]
if it means tmw

i am dck (look at all my old commits lol, i rename a lot), and when i went inactive my collab was removed

**Comment by PatheticMustan** [comment]
ah, alright

**Comment by ArcerionDev** [comment]
> > tmw DCK is cut out
> 
> what does tmw stand for

That moment when

**Pull request merged**
