### PR TITLE
move _.functions over to willsCheatMenu

### PR DESCRIPTION
**Pull request by PatheticMustan**
Move _.functions over to WCM, not a necessary change.
Up to Will to decide if this should be merged or not. If not, deny the related PR in Redirector.

[Related](https://github.com/Prodigy-Hacking/Redirector/pull/3)

Intent is to clean up some things, make it easier to add new things to WCM.
It seems a little strange to define stuff like getAllPets in Redirector, and makes fixing stuff in _.functions annoying.

### CODE REVIEW

**Comment by ArcerionDev** [comment]
woah a real pull request by mustan

**Comment by PatheticMustan** [comment]
unfunny

**Comment by ArcerionDev** [comment]
funny

**Comment by lol621** [comment]
hi

**Comment by lol621** [comment]
how do i hack

**Comment by UntrustableRus** [comment]
> how do i hack

Read the file that is literally called "README" [link](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/master/README.md)

**Comment by LifeIsNull** [comment]
> how do i hack

go to pornhub.com

**Comment by PatheticMustan** [comment]
whatever, merging already

**Comment by Fe4rlessfan121** [comment]
what do i edit for the this:

 //> Pet Level 100
//>> Sets all your pets to level 100.
_.player.kennel.data.map(x => x.level = 100);

**Comment by ArcerionDev** [comment]
nothing

**Pull request merged**
