### PR TITLE
Fix Firefox download link

### PR DESCRIPTION
**Pull request by UntrustableRus**
Fixes Firefox download link in README because it was moved.

### CODE REVIEW

**Comment by PatheticMustan** [comment]
Sorry about that ;((

**Comment by poIarbear** [comment]
GUYS WE SHOULD PUT ARC IN A JAIL CELL I CAUGHT HIM MURDERING A PUMPKIN

**Comment by poIarbear** [comment]
@everyone i have something to say.. arcy warcy is my wife.

**Comment by poIarbear** [comment]
not even kidding, i love my wife

**Pull request merged**
