### PR TITLE
Discord Arena Point Bot

### PR DESCRIPTION
**Pull request by irhrhd**
Ill update the code if i need to fix anything

## Description
I made a bot with my friend hostedposted on discord heres the code for it and you can hack your account with it and also farm points arena points i would like you guys to let me add this

### CODE REVIEW

**Comment by BoredFishRE** [comment]
sorry, we've already got an arenapoints thing that is in dev.

**Comment by ArcerionDev** [comment]
actually it's a good idea to have a bot for it

**Comment by ArcerionDev** [comment]
but we won't put it on the github, we'll host it somewhere else

**Comment by PatheticMustan** [comment]
alright

**Comment by ArcerionDev** [comment]
don't merge it yet

**Comment by ArcerionDev** [comment]
ignore that ^^

**Comment by ArcerionDev** [comment]
yeah we'll probably make something using discord.js instead of selenium to make it more compatible

**Comment by PatheticMustan** [comment]
make a PR to

https://github.com/Prodigy-Hacking/Research

**Comment by irhrhd** [comment]
Okay thanks Arcy and this is code for a discord bot me and my friend made

**Pull request closed without merging**
