### PR TITLE
adding a paragraph

### PR DESCRIPTION
**Pull request by hellonearth311**
## Description
This adds a bold paragraph saying it is created and maintained by the ProdigyMathGameHacking community.

### CODE REVIEW

**Comment by ChickenOnYT** [comment]
no its broken

**Comment by hellonearth311** [comment]
wut how?

**Comment by ChickenOnYT** [comment]
you put it outside of the quotes so now there's a random HTML tag in the JS

**Review by ChickenOnYT — COMMENTED** [review]
don't see the purpose of it, and it isnt really the community making all the changes, yknow the admins do a lot of it

**Comment by ArcerionDev** [comment]
I don't think this is needed, plus, too much text *will* clutter the menu

**Pull request closed without merging**
