### PR TITLE
fix 502

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by 32n** [comment]
???

**Comment by donaldli2020** [comment]
the domain changed

**Comment by donaldli2020** [comment]
and https://hacks.prodigyhacking.com broke

**Comment by donaldli2020** [comment]
alt https://prodigy-hacking.hostedposted.com/game.min.js

**Comment by ArcerionDev** [comment]
it doesn't work; it throws a cors error 
also, you didn't build the extension
also the regular site is coming back in two days

**Comment by 32n** [comment]
Not only that, but this is at best, not a great way to fix it, because hostedposted's site shouldn't be used as the primary source for the code. Also, no matter how small a pull request seems, you should always be testing and building the code, as well as verifying that it works, before submitting.

**Comment by ArcerionDev** [comment]
also I doubt hosted's hosting would be able to take the 2 million monthly requests we get regularly

**Comment by ArcerionDev** [comment]
hosted's hosting haha funny

**Comment by donaldli2020** [comment]
> also I doubt hosted's hosting would be able to take the 2 million monthly requests we get regularly

That's about 45 per minute

**Pull request closed without merging**
