### PR TITLE
adding that we will never hack your account for you.

### PR DESCRIPTION
**Pull request by hellonearth311**
## Description
I added that we will never hack your account for you.

### CODE REVIEW

**Comment by NX721** [comment]
That's already there, on a different place. Now close this please.

**Comment by hellonearth311** [comment]
its not there bro i hate u

**Comment by ChickenOnYT** [comment]
#170

**Comment by ChickenOnYT** [comment]
its on the top of discussions lol

**Comment by NX721** [comment]
> its not there bro i hate u

Lmao

**Comment by NX721** [comment]
Yeah I was right.

**Pull request closed without merging**
