### PR TITLE
Experimental hacks

### PR DESCRIPTION
**Pull request by Bonnie432**
Here’s a hack to Experiment

### CODE REVIEW

**Comment by Bonnie432** [comment]
Check my hack

**Comment by ArcerionDev** [comment]
changing the button name won't change the hack

**Comment by UntrustableRus** [comment]
Hey! As ArcerionDev said, changing the button name won't change the hack. Working on the project (mostly) requires knowledge of programming. However, thanks for atleast trying to add a feature to the hack.

**Comment by Bonnie432** [comment]
You are welcome guys

**Pull request closed without merging**
