### PR TITLE
space before comments for keeping code clean

### PR DESCRIPTION
**Pull request by DaChickenKing**
very minor change idea i had

### CODE REVIEW

**Comment by kayla-hue** [comment]
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/blob/3247f89b059de1cafc4fda6e981ecda9a9d092ba/willsCheatMenu/src/hacks/misc.ts

**Comment by kayla-hue** [comment]
Does that hack still works?

**Comment by kayla-hue** [comment]
Please tell me if it does or not 😕

**Comment by DaChickenKing** [comment]
@kayla-hue I am sorry, but there are better places to request hack support.

I can inform you that it will not work to run random parts of a script that requires compiling. Instead, please use our wiki page to set up Will's Cheat Menu.

**Comment by BoredFishRE** [comment]
> Please tell me if it does or not 😕

Hi! If you need support, please go to the discord! Me and others are ready to help!

**Comment by kayla-hue** [comment]
> > Please tell me if it does or not 😕
> 
> @kayla-hue Hi! If you need support, please go to the discord! Me and others are ready to help!

I dont have discord, is there a other way u can help out?

**Comment by kayla-hue** [comment]
> @kayla-hue I am sorry, but there are better places to request hack support.
> 
> I can inform you that it will not work to run random parts of a script that requires compiling. Instead, please use our wiki page to set up Will's Cheat Menu.

So it does not works? Also where is the wiki page, will's cheat menu?

**Comment by kayla-hue** [comment]
I just want my account to be Bobby fancywoman

**Comment by kayla-hue** [comment]
> I don't think that this is really necessary. Thanks for the thought, though.

Wut

**Comment by DaChickenKing** [comment]
@Avn1114 Okay, thanks 

@kayla-hue He is talking about the original topic of this PR - my code change.

**Comment by PatheticMustan** [comment]
@kayla-hue the discord is [here](https://discord.gg/XQDfbfq)

**Pull request closed without merging**
