### PR TITLE
#169

### LINKED ISSUE #169: Keep the folder and filenames camelCase!
I'm seeing PascalCase too much in hacks. Make sure the first letter is lowercase

### PR DESCRIPTION
**Pull request by PatheticMustan**
Fixes #169, but only renames the hacks/folders in /hack

### CODE REVIEW

**Comment by PatheticMustan** [comment]
somebody pls review

**Review by BoredFishRE — APPROVED** [review]
looks fine lmao

**Comment by coolsharc** [comment]
where the membership hack

**Comment by PatheticMustan** [comment]
@coolsharc membership hacks come with Redirector. Don't post in unrelated issues, please just read the instructions.

**Comment by coolsharc** [comment]
ok thanks

**Pull request merged**
