### PR TITLE
add another hack

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by 32n** [comment]
Please bundle this.

**Review by afkvido — APPROVED** [review]
i think it's a good idea

**Comment by afkvido** [comment]
> Please bundle this.

@donaldli2020

**Comment by afkvido** [comment]
32, he bundled it!

**Comment by donaldli2020** [comment]
i fixed the bundle because ${} doesn't work with " "

**Review by ArcerionDev — CHANGES_REQUESTED** [review]
image

your build is faulty.

use webpack.

we aren't going to ask you again.

**Comment by ArcerionDev** [comment]
if you don't know how-

install nodejs - https://nodejs.org/dist/v17.4.0/node-v17.4.0-x64.msi

install git - https://git-scm.com/download/win

```cmd
git clone https://github.com/Prodigy-Hacking/ProdigyMathGameHacking
# commit your changes in an IDE like VSCode
cd ProdigyMathGameHacking/willsCheatMenu
npm install webpack
set NODE_OPTIONS=--openssl-legacy-provider
npm run build
```

**Comment by donaldli2020** [comment]
I can`t download node

**Comment by donaldli2020** [comment]
image
image

**Comment by ArcerionDev** [comment]
what windows version do you have

**Comment by donaldli2020** [comment]
7

**Comment by ArcerionDev** [comment]
please update, this isnt 2009

**Comment by donaldli2020** [comment]
can you bundle this for me

**Comment by PatheticMustan** [comment]
i believe the bundle's already changed since then, I'll webpack after merging

**Comment by PatheticMustan** [comment]
i believe the bundle's already changed since then, I'll webpack after merging

**Comment by 32n** [comment]
> please update, this isnt 2009

~~or use linux hehe~~

**Comment by ArcerionDev** [comment]
@PatheticMustan cough cough you havent merged yet

**Comment by ArcerionDev** [comment]
*bundled yet, I reverted this until it's bundled

**Comment by PatheticMustan** [comment]
???! I could have sworn i did, mb

**Comment by afkvido** [comment]
> ???! I could have sworn i did, mb

;) looks like ya didn't

**Comment by afkvido** [comment]
> image
> image

you're using windows 7?

**Comment by 32n** [comment]
> ???! I could have sworn i did, mb

Yeah, I'm not sure what you're thinking sometimes. See ya next period nerd.

**Pull request merged**
