### PR TITLE
URGENT UPDATE

### PR DESCRIPTION
**Pull request by donaldli2020**
## Description

URL has been changed

### CODE REVIEW

**Comment by donaldli2020** [comment]
image

**Comment by afkvido** [comment]
@32n IMPORTANT

**Comment by ArcerionDev** [comment]
we were already aware of this
image

unfortunately this also breaks hacks.prodigyhacking.com , so we'll need to fix this first and foremost

and for GOD'S SAKE DONALDLI we arent going to merge your prs if you don't build the menu/extension

**Comment by donaldli2020** [comment]
what even is crx and xpi

**Comment by donaldli2020** [comment]
and i cant build the extension

**Comment by donaldli2020** [comment]
> what even is crx and xpi

idk how to generate them

**Comment by ArcerionDev** [comment]
> and i cant build the extension

please read the README.md in the PHEx folder.

**Comment by donaldli2020** [comment]
where do i run ```
npm i```

**Comment by ArcerionDev** [comment]
cmd

**Comment by ArcerionDev** [comment]
I think you should learn more about this before contributing, it'll make things a lot simpler.

**Comment by donaldli2020** [comment]
i dont have cmd

**Comment by 32n** [comment]
@donaldli2020
Before contributing further, you should do some of your own research on how JavaScript, Node.js, and npm work, as they are some of the most important tools/libraries that this project uses. Not that you have to know everything about them, but get a general sense of what they're used for and how to use them.

You've pushed builds in which you've edited the bundle manually without testing any of your code, forcing collaborators/maintainers to build the extension for you and test it. It's a pretty irresponsible thing to do, because as a contributor, you're expected to understand how the code works, and to test your code before contributing.

I know I haven't been the most understanding person, but I really do hope you actually consider what I'm saying, because it's a nuisance to a lot of us when you ask questions about things you should be expected to know before creating pull requests.

**Comment by ArcerionDev** [comment]
^

**Comment by afkvido** [comment]
@32n toxic lmao

ration + L + you're whiet + your gay

**Comment by afkvido** [comment]
ynkow imma try do this myself and see if  i can

**Comment by afkvido** [comment]
> i dont have cmd

**wdym** cmd = terminal

Linux = Terminal/Konsole
MacOS = iTerm/Terminal
Windows = Command Prompt/PowerShell

**Comment by 32n** [comment]
> > i dont have cmd
> 
> **wdym** cmd = terminal
> 
> Linux = Terminal/Konsole MacOS = iTerm/Terminal Windows = Command Prompt/PowerShell

This is sorta inaccurate. Linux is just a kernel. Your terminal is decided more by your choice of Terminal Emulator/WM/Desktop env/Distro. That's what's so nice about it! You don't have to have a crappy terminal like CMD shoved down your throat.

**Comment by 32n** [comment]
I assume you've just used distros with GNOME or KDE if you're just familiar with Konsole and GNOME Terminal.

**Comment by afkvido** [comment]
I guess

**Comment by LeoBadeaux** [comment]
> what even is crx and xpi

These are the bundled extensions for Firefox and some other browsers for cross-compatibility.

**Pull request closed without merging**
