### PR TITLE
Update and rename ConfettiSpam.js to SpamFx.js

### PR DESCRIPTION
**Pull request by DaChickenKing**

### CODE REVIEW

**Comment by TNThacker2015** [comment]
Remove the snowball spam, its already in another file.

**Comment by DaChickenKing** [comment]
Oh, sorry

**Comment by Diveodile** [comment]
I will put a "Get all furniture" hack.

**Comment by PatheticMustan** [comment]
Already have a get all furniture hack
https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/94f44e9320f3861434cd86853c674193d4eb950a/Items/Everything.js#L18

**Comment by Diveodile** [comment]
> Already have a get all furniture hack
> https://github.com/PatheticMustan/ProdigyMathGameHacking/blob/94f44e9320f3861434cd86853c674193d4eb950a/Items/Everything.js#L18

Thank you!

**Comment by MATEMATIK-SOSYE** [comment]
By the way, I recently added the crystal monster, and using Will's, every time I log in and go into the pet inventory, it would send me right back to the main page. Why does it do that?!

**Comment by MATEMATIK-SOSYE** [comment]
The word 'player' in codes has ALSO been removed. What is the replacement now?!

**Pull request closed without merging**
