### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BoredFishRE**

### CODE REVIEW

**Comment by DaChickenKing** [comment]
bruh how do i suggest changes

**Comment by BoredFishRE** [comment]
Just tell me lmao

**Comment by DaChickenKing** [comment]
my suggestion: change "legit" to "legitimate" or something like that because thats more formal

**Comment by BoredFishRE** [comment]
Change it once it's merged

**Comment by DaChickenKing** [comment]
kk

**Comment by PatheticMustan** [comment]
uh, the README has been updated since this PR has been made... I'll have to close this, but thanks for the typo fix.

**Pull request closed without merging**
