### PR TITLE
2021 Release

### PR DESCRIPTION
**Pull request by PatheticMustan**
Done
- Removed yamasMasterCheatMenu
- Removed arcsCheatMenu (let's be honest, nobody uses either, they're never updated)

Working On
- 2021 WCM updates
- Moving ArenaPoints to its own repo
- Planning to move Tokenify to its own repo

Future
- Planning to update typings (maybe its own package??)
- Planning on updating docs

### CODE REVIEW

**Comment by ArcerionDev** [comment]
seems legit

is it possible for others to add to a new branch lol

**Comment by ArcerionDev** [comment]
stupid question

**Comment by ArcerionDev** [comment]
nvm

**Comment by PatheticMustan** [comment]
> seems legit
> 
> is it possible for others to add to a new branch lol

you have write access, don't you 🤨

**Comment by ArcerionDev** [comment]
> > seems legit
> > is it possible for others to add to a new branch lol
> 
> you have write access, don't you 🤨

> stupid question
> nvm

**Comment by poIarbear** [comment]
ok

**Comment by sincerep205** [comment]
how do i add scripts to prodigy on a school chromebook

**Comment by sincerep205** [comment]
do you guys know

**Comment by poIarbear** [comment]
if your school chromebook allows external extensions to be imported after
turning on dev mode somewhere in the os settings then you can download the
file on discord and import that, currently the hacks are patched right now
so you'll have to wait

**Comment by BoredFishRE** [comment]
> 
> if your school chromebook allows external extensions to be imported after turning on dev mode somewhere in the os settings then you can download the file on discord and import that, currently the hacks are patched right now so you'll have to wait
No... they aren't

**Comment by PatheticMustan** [comment]
Hacks have been fixed for a while....

**Comment by poIarbear** [comment]
not up to date lol

**Comment by PatheticMustan** [comment]
stop posting on dead topics

**Pull request merged**
