### PR TITLE
Increase gold limit to 1 trillion.

### PR DESCRIPTION
**Pull request by hellonearth311**
## Description
Increase the gold limit because its annoying to only get 10 million gold.

### CODE REVIEW

**Comment by TheFinality** [comment]
no

**Comment by 32n** [comment]
@hellonearth311 please see #1183

**Comment by donaldli2020** [comment]
You can do that using code
```
_.player.data.gold = 1e+12;
```

**Comment by 32n** [comment]
...but there is no point in doing that, as it will immediately crash your game and you won't end up having that much gold when you log in again.

**Comment by donaldli2020** [comment]
:+1:

**Pull request closed without merging**
