### PR TITLE
maybe fix skids from asking about developer options?

### PR DESCRIPTION
**Pull request by afkvido**
## Description
maybe fix skids from asking about developer options?

changing the phex popup
also, please for the love of god someone webpack this for me if that's needed, i'm too retarded to do that myself

## Screenshots
since i'm too retarded to build, here's the html loaded as a webpage
image

### CODE REVIEW

**Comment by 32n** [comment]
The UI seems pretty clear to me, honestly. Your thoughts @PatheticMustan?

**Comment by afkvido** [comment]
> The UI seems pretty clear to me, honestly. Your thoughts @PatheticMustan?

YAAAAAY
I DON'T HAVE TO WEBPACK LETS GOOOOOO

**Comment by 32n** [comment]
> > The UI seems pretty clear to me, honestly. Your thoughts @PatheticMustan?
> 
> YAAAAAY I DON'T HAVE TO WEBPACK LETS GOOOOOO

That's not what I said :P

**Comment by PatheticMustan** [comment]
LGTM

**Comment by ArcerionDev** [comment]
ya still have to build the extension

**Review by PatheticMustan — APPROVED** [review]

**Comment by PatheticMustan** [comment]
For future reference I'm pretty sure there's a build.js script you can just run.

**Comment by ArcerionDev** [comment]
you need to install some deps, not sure if kozel knows how to do that

**Comment by 32n** [comment]
@PatheticMustan why didn't you bundle the changes???

**Comment by ArcerionDev** [comment]
> @PatheticMustan why didn't you bundle the changes???

image

**Comment by 32n** [comment]
messy way to do things imo cuz now bundling will be in a separate commit instead of squashed with this.

**Comment by afkvido** [comment]
> you need to install some deps, not sure if kozel knows how to do that

i tried npm install, still couldnt build/pack

im bad with npm

**Comment by afkvido** [comment]
> messy way to do things imo cuz now bundling will be in a separate commit instead of squashed with this.

**yes**, its a very messy way to do it.
but i am dum dum

**Comment by 32n** [comment]
No, I was talking about Mustan merging without building the extension, so he'll need to create another commit where he builds it.

**Comment by afkvido** [comment]
> No, I was talking about Mustan merging without building the extension, so he'll need to create another commit where he builds it.

ik

**Pull request merged**
