### PR TITLE
custom dropdown

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by donaldli2020** [comment]
testing...

**Comment by donaldli2020** [comment]
someone help me webpack this

**Comment by ArcerionDev** [comment]
please refer to [this comment](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/pull/1299#issuecomment-1023663953).

**Comment by donaldli2020** [comment]
#1309

**Comment by afkvido** [comment]
@ArcerionDev, donaldli was just tryin to fix #1309

**Comment by 32n** [comment]
@afkvido donaldli literally does not listen to maintainers. We've attempted to point him in the right direction, and send him resources on how to use node.js and webpack. He still commits untested code, forcing us to build and test his code for him. His changes are too inconsequential for it to be worth entertaining any of his pull requests, and he is STILL MANUALLY EDITING THE BUNDLE and does not have node.js installed.

**Comment by afkvido** [comment]
> @afkvido donaldli literally does not listen to maintainers. We've attempted to point him in the right direction, and send him resources on how to use node.js and webpack. He still commits untested code, forcing us to build and test his code for him. His changes are too inconsequential for it to be worth entertaining any of his pull requests, and he is STILL MANUALLY EDITING THE BUNDLE and does not have node.js installed.

Ok, that explains it.

**Comment by afkvido** [comment]
> someone help me webpack this

npm i
npm install webpack
npm build

**Comment by 32n** [comment]
> > someone help me webpack this
> 
> npm i npm install webpack npm build

the amount of times we have spoonfed him these commands is ridiculous. Arc asked Nat to ban donaldli from making PRs until he learns how to code and installs nodejs.

**Comment by afkvido** [comment]
;( sadge

**Pull request closed without merging**
