### PR TITLE
Removed link to my profile

### PR DESCRIPTION
**Pull request by SwxtchCode**
I don't want it to link to me anymore. Also, can someone delete this PR once it's merged?

### CODE REVIEW

**Comment by SwxtchCode** [comment]
@ArcerionDev

**Comment by SwxtchCode** [comment]
@ArcerionDev can you delete this PR

**Comment by PatheticMustan** [comment]
I don't think PRs can be deleted

**Comment by SwxtchCode** [comment]
oh shoot that's right

**Pull request merged**
