### PR TITLE
It's time I think

### PR DESCRIPTION
**Pull request by afkvido**
## Description
https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/ebf6eb9c1396b66b08b1b3b70a908728ce6c2e6b [(this)](https://github.com/Prodigy-Hacking/ProdigyMathGameHacking/commit/ebf6eb9c1396b66b08b1b3b70a908728ce6c2e6b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) was a month ago, I think it's been there for enough time.

## Screenshots
image

### CODE REVIEW

**Comment by 32n** [comment]
Yama is the supreme ruler of the README. Let us ask for his opinions.

**Comment by 32n** [comment]
Actually I change my mind this is sort of a low effort README pr and should just be closed.

**Comment by afkvido** [comment]
> Actually I change my mind this is sort of a low effort README pr and should just be closed.

Yama is the supreme ruler of the README. Let us ask for his opinions.

**Comment by afkvido** [comment]
just because you don't like README prs doesn't mean they should all be eradicated from existence
you're acting about README prs like h1tler was acting about people of other nationalities.

be open to useful PRs, just because someone can't directly push doesn't mean someone doesn't deserve to have a chance for a review of a PMGH Maintainer (Mustan in this case)

### you're very closed minded. if you want to keep README prs away, then consider making a CONTRIBUTING.md

###### donalidi > 32n.

**Comment by 32n** [comment]
As you wish. @YamaHacks

**Comment by afkvido** [comment]
LMAO, ty Arcerion <3

**Pull request merged**
