### PR TITLE
fix achievements

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by donaldli2020** [comment]
#1212

**Comment by donaldli2020** [comment]
tested

**Comment by donaldli2020** [comment]
and working

**Comment by 32n** [comment]
LGTM. I'm not sure if the maintainers would be fine with me using my write perms to merge, so I'll leave that to them.

**Comment by PatheticMustan** [comment]
??? wait why did re-building change anything, didn't you already build it?

**Pull request merged**
