### PR TITLE
Add a little detail.

### PR DESCRIPTION
**Pull request by hellonearth311**
## Description
Add the Zendesk blocking thing.

### CODE REVIEW

**Review by afkvido — APPROVED** [review]
I like this idea

**Comment by ArcerionDev** [comment]
this is honestly super inconsequential, please refrain from making prs like this in the future, only make prs that are actually relevant.

i'll merge this one but this is the last one liner i'm merging from you, or anyone

**Comment by afkvido** [comment]
> this is honestly super inconsequential, please refrain from making prs like this in the future, only make prs that are actually relevant.
> 
> i'll merge this one but this is the last one liner i'm merging from you, or anyone

if you didn't like his pr, then why'd u merge it?

**Comment by ArcerionDev** [comment]
because I might as well but these prs are just super annoying

**Comment by afkvido** [comment]
oh ok

**Comment by 32n** [comment]
> this is honestly super inconsequential, please refrain from making prs like this in the future, only make prs that are actually relevant.
> 
> i'll merge this one but this is the last one liner i'm merging from you, or anyone

Thanks, Arc. The larger a project like this scales, the more annoying it is to test these sorts of super tiny/inconsequential PRs.

**Comment by afkvido** [comment]
Test? This is a pure README pr

**Pull request merged**
