### PR TITLE
The sentense is incomplete

### PR DESCRIPTION
**Pull request by donaldli2020**

### CODE REVIEW

**Comment by JeaIousy** [comment]
compile it please

**Comment by donaldli2020** [comment]
What's compile?

**Comment by JeaIousy** [comment]
use webpack to compile wcm

**Comment by donaldli2020** [comment]
What's webpack?

**Comment by JeaIousy** [comment]
npm i -g webpack, then cd to prodigymathgamehacking/willlscheatmenu, then write webpack in console

**Pull request merged**
