### PR TITLE
Create Infinite Tower Level

### PR DESCRIPTION
**Pull request by RoundEggy**
Oooh Yeaaahhh prodigy is hackeddd

### CODE REVIEW

**Review by RoundEggy — COMMENTED** [review]
This is my first time doing this. I hope you like it!

**Comment by ArcerionDev** [comment]
Already able to be done with wcm, closing

**Comment by SwxtchCode** [comment]
assume good faith

**Comment by PatheticMustan** [comment]
it's not even original????

**Comment by RoundEggy** [comment]
> Already able to be done with wcm, closing

oops

**Comment by RoundEggy** [comment]
> it's not even original????

wat ok bye

**Pull request closed without merging**
