### PR TITLE
rename Easy Mode to Disable Math

### PR DESCRIPTION
**Pull request by afkvido**
## Description
rename Easy Mode to Disable Math

I ACTUALLY BUNDLED THIS

## Screenshots
rename Easy Mode to Disable Math

### CODE REVIEW

**Comment by afkvido** [comment]
I ACTUALLY BUNDLED THIS, ARE Y'ALL PROUD OF ME

**Comment by 32n** [comment]
> I ACTUALLY BUNDLED THIS, ARE Y'ALL PROUD OF ME

lol yes im very proud

**Comment by ArcerionDev** [comment]
what could do wrong

**Comment by 32n** [comment]
Not merging tiny commits isn't only to discourage unimportant contributions, it's something we should seriously consider doing because it could cause major security issues.

**Comment by ArcerionDev** [comment]
yeah I understand what you mean

**Comment by afkvido** [comment]
;) YESSSSS, FINALLY I MANAGED TO MAKE A SUCCESSFUL PR

THIS IS MY HAPPIEST DAY ON THIS REPO

**Comment by 32n** [comment]
I will be happy when I make a meaningful contribution.

**Comment by 32n** [comment]
My PRs are sorta bad too lmao.

**Comment by afkvido** [comment]
> I will be happy when I make a meaningful contribution.

;) youre a collaborator

**Comment by 32n** [comment]
Only because I know Natsumi irl and he knows I am somewhat competent at coding.

**Comment by afkvido** [comment]
lmao

**Comment by afkvido** [comment]
I'm ngl, the main purpose of this PR was to see if I could bundle it correctly.

yay, I could :)

**Comment by 32n** [comment]
> I'm ngl, the main purpose of this PR was to see if I could bundle it correctly.
> 
> yay, I could :)

Then don't make a PR...

**Comment by afkvido** [comment]
> > I'm ngl, the main purpose of this PR was to see if I could bundle it correctly.
> > yay, I could :)
> 
> Then don't make a PR...

my contribution was actually helpful tbh.... "Easy Mode" isn't actually very descriptive.

**Comment by 32n** [comment]
A drop in the ocean.

**Comment by afkvido** [comment]
;)

**Pull request merged**
