### PR TITLE
Click teleport interval

### PR DESCRIPTION
**Pull request by PatheticMustan**
Currently "toggle click teleport" resets whenever player travels to a new scene, change it to an interval.

On enable: setInterval.
On disable: clearInterval and set walkspeed to 1.5x

### CODE REVIEW

**Comment by PatheticMustan** [comment]
with the power vested in me, I do the ultimate funny

**Comment by afkvido** [comment]
Toggle Click Teleport **still** resets on zone switch

**Comment by 1603191909** [comment]
i dont think so
not for me

**Comment by afkvido** [comment]
imma check

**Comment by 1603191909** [comment]
last used it like a few weeks ago

**Pull request merged**
